let sapMSelect = new sap.m.Select({
    autoAdjustWidth: false,
    busy: false,
    busyIndicatorDelay: 1000,
    busyIndicatorSize: 'Medium',
    columnRatio: '3:2',
    editable: true,
    enabled: true,
    fieldGroupIds: [],
    forceSelection: true,
    icon: '',
    maxWidth: '100%',
    name:'',
    required: false,
    resetOnMissingKey: false,
    selectedItemId: '',
    selectedKey: 0,
    showSecondaryValues: false,
    textAlign: 'Initial',
    textDirection: 'Initial',
    type: 'Default',
    valueState: 'None',
    valueStateText: '',
    visible: true,
    width: 'auto',
    wrapItemsText: false
});