const sapUiTableTable = new sap.ui.table.Table({
    alternateRowColors: false,
    busy: true,
    busyIndicatorDelay: 1000,
    busyIndicatorSize: 'Medium',
    columnHeaderVisible: true,
    editable: true,
    enableBusyIndicator: true,
    enableCellFilter: false,
    enableColumnFreeze: false,
    enableColumnReordering: false,
    enableGrouping: false,
    enableSelectAll: true,
    fieldGroupIds: [],
    firstVisibleRow: 0,
    fixedBottomRowCount:0,
    fixedColumnCount: 0,
    fixedRowCount: 0,
    minAutoRowCount: 4,
    rowActionCount: 0,
    selectedIndex: -1,
    selectionBehavior: 'RowSelector',
    selectionMode: 'MultiToggle',
    showColumnVisibilityMenu: false,
    showNoData: true,
    showOverlay: false,
    threshold: 100,
    visible: true,
    visibleRowCount: 10,
    visibleRowCountMode: 'Fixed',
    width: 'auto'
})
