<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<DIV id="main" style="display:"> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 보안관리</b></font><br>
<div id='div1000000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sec/ram/CoreAuthorList.cm');>― 권한관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sec/gmt/EgovGroupList.cm');>― 그룹관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sec/rgm/EgovAuthorGroupList.cm');>― 권한그룹관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sec/rmt/CoreRoleList.cm');>― 롤관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sec/drm/EgovDeptAuthorList.cm');>― 부서권한관리</a></font><br>
</div> 
<br> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 사용자지원</b></font><br>
<div id='div2000000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 메뉴관리</b></font><br>
<div id='div2010000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/mnu/mpm/coreMenuManageList.cm');>― 메뉴목록관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/mnu/mpm/coreMenuList.cm');>― 메뉴리스트</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/mnu/mcm/EgovMenuCreatManageSelect.cm');>― 메뉴생성관리</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 프로그램관리</b></font><br>
<div id='div2020000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/prm/coreProgrmList.cm');>― 프로그램목록관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/prm/EgovProgramChangeRequstSelect.cm');>― 프로그램변경관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/prm/EgovProgramChangeRequstProcessListSelect.cm');>― 프로그램변경요청</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/prm/coreProgrmCngHstList.cm');>― 프로그램변경이력</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 사용자관리</b></font><br>
<div id='div2030000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/umt/EgovUserManage.cm');>― 업무사용자관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/umt/EgovMberManage.cm');>― 일반회원관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/umt/EgovEntrprsMberManage.cm');>― 기업회원관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/umt/EgovStplatCnfirmMber.cm');>― 일반회원가입처리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/umt/EgovStplatCnfirmEntrprs.cm');>― 기업회원가입처리</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olp/mgt/EgovMeetingManageList.cm');>― 회의관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 설문관리</b></font><br>
<div id='div2050000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olp/qtm/EgovQustnrTmplatManageList.cm');>― 설문템플릿관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olp/qmc/EgovQustnrManageList.cm');>― 설문지관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olp/qqm/EgovQustnrQestnManageList.cm');>― 설문문항관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olp/qim/EgovQustnrItemManageList.cm');>― 설문항목관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olp/qri/EgovQustnrRespondInfoList.cm');>― 설문조사(응답결과)관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olp/qnn/EgovQustnrRespondInfoManageList.cm');>― 설문참여</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olp/qrm/EgovQustnrRespondManageList.cm');>― 설문응답자정보관리</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/sam/stp/StplatListInqire.cm');>― 약관관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/sam/cpy/CpyrhtPrtcPolicyListInqire.cm');>― 저작권보호정책관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 상담관리</b></font><br>
<div id='div2080000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olp/cns/CnsltListInqire.cm');>― 상담목록조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olp/cnm/CnsltAnswerListInqire.cm');>― 상담답변목록조회</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olh/hpc/HpcmListInqire.cm');>― 도움말관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olh/wor/WordDicaryListInqire.cm');>― 용어사전관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olh/faq/FaqListInqire.cm');>― FAQ관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ Q&A관리</b></font><br>
<div id='div2120000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olh/qna/QnaListInqire.cm');>― Q&A목록조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/olh/qnm/QnaAnswerListInqire.cm');>― Q&A답변목록조회</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/ion/nws/NewsInfoListInqire.cm');>― 뉴스관리</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 사이트관리</b></font><br>
<div id='div2210000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/ion/sit/SiteListInqire.cm');>― 사이트목록조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/CorePageLink.cm?link=/coreframework/com/sym/mnu/stm/EgovSiteMap');>― 사이트맵</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/ion/rec/RecomendSiteListInqire.cm');>― 추천사이트관리</a></font><br>
</div> 
<br> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 사용자인증</b></font><br>
<div id='div3000000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uat/uia/coreLoginUsr.cm');>― 로그인</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uat/uia/egovIdPasswordSearch.cm');>― ID/PW찾기</a></font><br>
</div> 
<br> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 시스템관리</b></font><br>
<div id='div4000000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 로그조회</b></font><br>
<div id='div4010000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/log/lgm/coreSysLogList.cm');>― 시스템로그조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/log/tlg/SelectTrsmrcvLogList.cm');>― 송수신로그조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/log/ulg/SelectUserLogList.cm');>― 사용로그조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/log/slg/SelectSysHistoryList.cm');>― 시스템이력조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/log/wlg/SelectWebLogList.cm');>― 웹로그조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/log/clg/SelectLoginLogList.cm');>― 접속로그조회</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/ccm/ccc/EgovCcmCmmnClCodeList.cm');>― 공통분류코드목록</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/ccm/cde/EgovCcmCmmnDetailCodeList.cm');>― 공통상세코드목록</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/ccm/cca/EgovCcmCmmnCodeList.cm');>― 공통코드목록</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/ccm/zip/EgovCcmZipList.cm');>― 우편번호목록</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/ccm/adc/EgovCcmAdministCodeList.cm');>― 행정코드목록</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sym/cal/EgovRestdeList.cm');>― 휴일목록</a></font><br>
</div> 
<br> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 협업</b></font><br>
<div id='div5000000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 게시판</b></font><br>
<div id='div5010000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/cop/bbs/SelectBBSMasterInfs.cm');>― 게시판목록조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/cop/com/selectBBSUseInfs.cm');>― 게시판 사용정보 조회</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 커뮤니티/동호회</b></font><br>
<div id='div5020000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/cop/cmy/selectCmmntyInfs.cm');>― 커뮤니티목록조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/cop/clb/selectClubInfs.cm');>― 동호회목록조회</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 공통관리</b></font><br>
<div id='div5030000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/cop/tpl/selectTemplateInfs.cm');>― 템플릿 목록조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/cop/com/selectConfirmRequest.cm');>― 승인정보조회</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 명함관리</b></font><br>
<div id='div5040000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/cop/ncm/selectNcrdInfs.cm');>― 명함목록조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/cop/ncm/addNcrdInf.cm');>― 명함등록</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 행사/이벤트/캠페인</b></font><br>
<div id='div5050000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/ion/ecc/EgovEventCmpgnList.cm');>― 행사/이벤트/캠페인 조회</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/uss/ion/ecc/EgovTnextrlHrInfoList.cm');>― 외부인사정보 조회</a></font><br>
</div> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 자료실 예시</b></font><br>
<div id='div5060000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/selectBoardList.cm?bbsId=BBSMSTR_000000000061');>― 자료실</a></font><br>
</div> 
</div> 
<br> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 통계/리포팅</b></font><br>
<div id='div6000000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sts/bst/selectBbsStats.cm');>― 게시물통계</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sts/ust/coreUserStatsList.cm');>― 사용자통계</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sts/bst/selectScrinStats.cm');>― 화면통계</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/sts/cst/selectConectStats.cm');>― 접속통계</a></font><br>
</div> 
<br> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' >+<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2><b>▶ 전자우편연계</b></font><br>
<div id='div7000000'> 
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/cop/ems/selectSndngMailList.cm');>― 발송메일내역</a></font><br>
<img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><img src="<c:url value='/images/coreframework/com/cmm/utl/menu_empty.gif'/>" border='0' align='absbottom' alt='' ><font size=2 class='.location'><a href=javascript:fCallUrl('/cop/ems/insertSndngMailView.cm');>― 발송메일등록</a></font><br>
</div> 
</DIV>